### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by TallGirlVanessa** [mikeymakesit/oglaf-meta#1]
I kinda wanna make a search engine out of this. I can't promise I actually will, but, a license would make it easier to derive new stuff off this.

**Comment by mikeymakesit** [comment]
Added GPLv3 in commit fee1a77.  Cheers and have fun!

**Comment by TallGirlVanessa** [comment]
I did it lmao. https://oglafsearch.com/

**Comment by mikeymakesit** [comment]
Looks great, you rock!
